### ISSUE TITLE
practica 1 

### ISSUE THREAD

**Issue by yaritzaov123** [SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-julio-cesar-gonzalez-lopez#2]
[practica 1.pdf](https://github.com/SistemasTecTlaxiaco/practica-logica-proposicional-y-tablas-de-verdad-equipo-julio-cesar-gonzalez-lopez/files/7524776/practica.1.pdf)

**Comment by Julissamigdalia** [comment]
Su trabajo está bien solo faltó las conclusiones de cada actividad. 94 puntos 28%.

**Comment by josealfredo79** [comment]
No es necesario insertar en la practica la teoria

**Comment by josealfredo79** [comment]
Se necesitan por favor hacer la descripcion mas detallada de los ejercicios...

**Comment by josealfredo79** [comment]
Revisado
